export const templates = [
 {id:'starter',name:'Cozy Starter House',emoji:'🏡',size:'9 × 7',difficulty:'Easy',time:'15 min',blocks:['Oak planks × 96','Cobblestone × 48','Oak logs × 28','Glass panes × 12','Oak stairs × 36','Door × 1','Torches × 6'],steps:[['Foundation','Mark a 9 × 7 rectangle. Replace the outer edge with cobblestone.'],['Frame','Place oak logs 4 blocks high on all four corners. Add logs beside the door.'],['Walls','Fill between logs with oak planks, leaving a 2-block door and 2 × 2 window gaps.'],['Windows','Place glass panes in every window gap and add the oak door.'],['Roof','Add an overhanging stair roof from both long sides. Close both gable ends with planks.'],['Finish','Add torches, a bed, crafting table, furnace and two flower boxes.']]},
 {id:'tower',name:'Survival Watchtower',emoji:'🗼',size:'7 × 7',difficulty:'Medium',time:'25 min',blocks:['Cobblestone × 144','Spruce logs × 52','Spruce planks × 64','Spruce fences × 28','Ladders × 14','Torches × 8'],steps:[['Base','Build a 7 × 7 cobblestone foundation.'],['Supports','Raise four spruce corner pillars to 12 blocks.'],['Floors','Place a plank floor at heights 5 and 11. Keep a ladder opening.'],['Lower walls','Use cobblestone between the pillars up to height 4.'],['Lookout','Create a 7 × 7 top room with one-block windows on each side.'],['Balcony','Extend the top floor one block outward and surround it with fences.'],['Roof','Use spruce stairs for a pointed roof and light every level.']]},
 {id:'bridge',name:'Medieval Bridge',emoji:'🌉',size:'5 × 15',difficulty:'Medium',time:'30 min',blocks:['Stone bricks × 180','Stone brick stairs × 64','Spruce planks × 45','Spruce fences × 32','Lanterns × 8'],steps:[['Path','Mark a 5 × 15 bridge path across the gap.'],['Piers','Build two 5-wide stone piers down to solid ground or the riverbed.'],['Arch','Create a stair-stepped stone arch from both banks toward the centre.'],['Deck','Lay a 3-wide spruce plank path with stone-brick edges.'],['Rails','Add spruce fence rails, leaving openings at the ends.'],['Details','Place lanterns every four blocks and mix cracked stone bricks for age.']]}
];

export function fallbackPlan(prompt){
 const name=(prompt||'Custom Minecraft Build').trim();
 return {id:'ai-'+Date.now(),name,emoji:'✨',size:'Custom',difficulty:'Custom',time:'Varies',blocks:['Main building block × estimate after measuring','Accent block','Stairs/slabs','Glass','Lighting'],steps:[['Measure','Choose the width, depth and maximum height. Keep odd dimensions for a clear centre line.'],['Outline','Mark every corner and entrance with temporary blocks. Check the shape from a distance.'],['Foundation','Fill the footprint and raise the base one block above the terrain.'],['Structure','Build corner pillars first, then connect them floor by floor.'],['Walls','Fill one repeated wall section at a time. Leave planned doors and windows open.'],['Roof','Start with the outer overhang, then work inward symmetrically.'],['Detail','Add depth with stairs, slabs, trapdoors, lighting and landscaping.']]};
}
